file=open("journey.txt","w")
file.write("all my journey:\n")
file.write("1.basics of python\n")
file.write("2.main python\n")
file.write("3.file handeling\n")
file.write("4.oops\n")
file.write("5.pandas\n")
file.write("6.num.py\n")
file.write("7.data visualization\n")
file.write("8.sql\n")
file.write("9.statistics\n")
file.write("10.EDA\n")
file.write("11.machine learning\n")
file.write("12.advanced ML\n")
file.close()
file=open("journey.txt","r")
read=file.read()
print(read)

